### ISSUE TITLE
error: unknown option `--from-code'

### ISSUE THREAD

**Issue by DmitriyBerezin** [mozilla/i18n-abide#107]
I try to generate .pot file from Jade templates according the documentation: https://github.com/mozilla/i18n-abide/blob/master/docs/GETTEXT.md. The command

```
./node_modules/.bin/extract-pot --locale locale .
```

throw an error

```
error: unknown option `--from-code'
```

The following packages are declared in my `packages.json`:

```
"i18n-abide": "0.0.25",
"jsxgettext": "^0.8.2"
```

**Comment by Bolik** [comment]
+1

**Comment by germanio** [comment]
+1
extract-pot is a wrapper of jsxgettext, if you look at the options it has, it does not support that option (any more?).
The same is happening with -l option, which is supposed to map "language" option, but jsxgettext supports "-L".
