### ISSUE TITLE
Update npm contributor list

### ISSUE THREAD

**Issue by vladikoff** [mozilla/i18n-abide#110]
Hey @fmarier or @zaach could you please add:

`vladikoff`
`stomlinson`

to https://www.npmjs.com/package/i18n-abide Collaborators list ?

Thanks!

**Comment by fmarier** [comment]
I tried this:

    npm access grant read-write stomlinson i18n-abide

but npm is asking for a team:

    npm ERR! team is required and must be of type string
    npm ERR! 
    npm ERR! Usage:
    ...
    npm ERR! npm access grant <read-only|read-write> <scope:team> [<package>]

 and I can't figure out how to add an individual person as an owner of that package.

**Comment by vladikoff** [comment]
@fmarier you can just use the npm website, login and there will be a + button on the module page. Thanks again!

**Comment by fmarier** [comment]
> you can just use the npm website, login and there will be a + button on the module page.

That's cheating! ;)
