### ISSUE TITLE
extract-pot assumes .ejs templates

### ISSUE THREAD

**Issue by ozten** [mozilla/i18n-abide#49]
If your templates have a different extension, such as `.html`, then extract-pot will blow up:

    input argument is required

    Usage: jsxgettext <input>... [options]

    input     input files

    Options:
       -o FILE, --output FILE     write output to specified file
       -p DIR, --output-dir DIR   output files will be placed in directory DIR
       -v, --version              print version and exit
       -k WORD, --keyword WORD    additional keyword to be looked for
       -j, --join-existing        join messages with existing file
       -L NAME, --language NAME   recognise the specified language (JS, EJS)

**Comment by zaach** [comment]
Looks like this is supported now here: https://github.com/mozilla/i18n-abide/blob/master/bin/extract-pot#L21
