### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by jpacora** [mozilla/i18n-abide#66]
Hello, i have this en_US locale:
http://pastebin.com/ffkxZPfe
And es_PE locale:
http://pastebin.com/eH7xVncN
And when i with my browser to en_US locale it doesn't work! But when i set to it-CH i see all text flipped. Im using express 3 with EJS and this code:

  app.use(i18n.abide({
    supported_languages: ['en_US', 'es_PE'],
    default_lang: 'en_US',
    translation_directory: 'i18n'
  }))

**Comment by zaach** [comment]
reopen if still a problem
