### ISSUE TITLE
Using gettext outside of routes

### ISSUE THREAD

**Issue by mbuttu** [mozilla/i18n-abide#86]
Hello,

Is it possible to use `gettext` outside of a route? We would like to localize our validation error messages, which all live in a central place in our code base.

For example, is it possible to do something like the following code?

``` javascript
// error-messages.js
module.exports = {
  required: gettext("This field is required")
};
```

``` javascript
// app.js
var errorMessages = require("./error-messages");

app.get("/test", function(req, res) {
  res.send({
    error: errorMessages.required
  });
});
```

Thanks!

**Comment by brunobg** [comment]
Any news here?

**Comment by alisamar** [comment]
+1

**Comment by richardpenner** [comment]
Did anyone figure this out?

**Comment by ozten** [comment]
Sorry, I missed these messages, my bad.

I would leave the strings in the module and then localize them at runtime during the request.

Why? You need to know the user's preferred locale to look up the correct localization. Currently the abstraction is to go through the request object, which gets this out of HTTP headers.

Depending on how you setup your express app, I think gettext is available from the request object (or you [could make it available from the response object](http://expressjs.com/en/api.html#res.locals)).

	// app.js
	var errorMessages = require("./error-messages");

	app.get("/test", function(req, res) {
	  res.send({
	    error: req.gettext(errorMessages.required)
	  });
	});

What is the use case? How will you know which locale you want?

If you really want this, I think you'd want to re use the low level code and design a new API that takes the locale and the string as an argument. I'd probably give it a different name to keep this library focused on it's use cases. Maybe i18n-abide-utils or i18n-abide-offline or something.

**Comment by richardpenner** [comment]
My use case is outside of a request context. E.g. if someone comments on something a user posted and I want to send a push notification, or perhaps an email is sent out a day after the user joins. In those cases we need to specify the language manually and outside the context of express. Yet I'd like all of my various platform components localized with the same framework, ideally, and this project does some nice things that other node gettext implementations don't do.

I actually think this module is pretty close to supporting this behaviour. As a test, I faked a request, response and next() object, hooked into the express plugin, and based on a simple test it looks like it's returning the right strings.

Are you interested in a PR? If so, any guidelines would be welcome.

**Comment by ozten** [comment]
Cool, mocking out the request will definitely work, but isn't clean code as it violates the encapsulation of the existing API.

Your code sounds very helpful to many people. If you don't want to create a new project, then...

I'm not actively working on i18n-abide, so I'd recommend a pull request that lands your code into a `contrib` directory. That way others can benefit, but it's clearly marked as something this team hasn't committed to from an API perspective.

Thanks for your awesome work!
