### ISSUE TITLE
res.locals is clobbered during initialization

### ISSUE THREAD

**Issue by ricardograca** [mozilla/i18n-abide#89]
When using the i18n-abide module on an Express app, any previously defined values in `res.locals` disappear. Example:

```
app.use(function(req, res, next) {
  res.locals.x = true
  next()
})
app.use(i18n.abide({ /* ... */ }))
app.use(function(req, res, next) {
  console.log(res.locals.x) // prints undefined
  next()
})
```

In the above example, if I remove the `i18n-abide` line, the last middleware prints `true` as expected.

Express 4.10.4, i18n-abide 0.0.22.

**Comment by zaach** [comment]
Looks like this was fixed.

**Comment by ricardograca** [comment]
I don't think it was. The current code is still overriding any previously defined `res.locals` in [this line](https://github.com/mozilla/i18n-abide/blob/master/lib/i18n.js#L263). I can provide a new PR if there's a chance it will get merged.

**Comment by zaach** [comment]
Ah, you're right. Just @ me in the PR and I'll take a look!

**Comment by JohnXLivingston** [comment]
I just made a PR for a fix here: https://github.com/mozilla/i18n-abide/pull/119
Can you please accept it?
