### ISSUE TITLE
How can I change default_lang via API?

### ISSUE THREAD

**Issue by michelem09** [mozilla/i18n-abide#95]
As per title is there a way to set the locale globally via API?
I see there is req.setLocale() but this sets the locale only for a single request while I'd like to set it globally.

**Comment by lexoyo** [comment]
I believe it is in the config, is `default_lang` what you are looking for?
```
var i18n = require('i18n-abide');

app.use(i18n.abide({
  supported_languages: ['en-US', 'de', 'es', 'db-LB', 'it-CH'],
  default_lang: 'en-US',
  debug_lang: 'it-CH',
  translation_directory: 'i18n'
}));
```
If you want to change options after creation, I think it is not possible :-/

**Comment by michelem09** [comment]
Yeah I know there is in initial config, but how can I change it after it's initialised?
It's incredible there isn't a way to do it.

**Comment by lexoyo** [comment]
It would be easy to add a `setDefaultLang` method but the thing is you would have to do [this loop again](https://github.com/mozilla/i18n-abide/blob/43c86b552cede4efa54f6679a3098bff9d15486e/lib/i18n.js#L93) and this means load the language file again. I am not sure if this is a good idea :-/

**Comment by victorgaspar** [comment]
Hi,

I have a solution that might fit your needs.

First, set a middleware in Node.JS
`
// If the locale cookie is set
// Use it for each request
function setLocaleCookie(request, response, next) {
	request.setLocale(request.cookies.locale);
	next();
};
app.use(setLocaleCookie);
`

Second, at some point in your application, set the cookie according to your needs:
`
	// set a cookie to requested locale
	app.get('/setlocale/:locale', function (request, response) {		
		response.cookie('locale', request.params.locale);
		response.redirect('back');
	});
`
Each request done to the server will contain the locale cookie, and the custom middleware will setLocale() as per request basis.

Hope it helps.

Regards,
V.

**Comment by germanio** [comment]
@victorgaspar your solution worked very well on my project. Thanks!
I would just add an `if` in the middleware function to check if the cookie is actually set (well, I don't know what happens if we try to set a locale with `null` or `undefined`). That case will happen the first time the user request the page.

**Comment by JohnXLivingston** [comment]
@victorgaspar , you missed the point. The setLocal method does not work with the debug_lang, as @michelem09 reported. The only way to use the db_LB debug locale is to set the browser lang to debug_lang. It is very annoying. 
i18n-abide should offer other solutions than locale_on_url to compute the locale without using the setLocal method. Like reading a cookie or a session parameter.
